### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by chenzhanglu** [Easquel/WaveDM#3]
File "/public/home/acplz3jcvc/czl/WaveDM/models/arch.py", line 250, in forward
    x = x + enc_skip
RuntimeError: The size of tensor a (74) must match the size of tensor b (75) at non-singleton dimension 2

I have tried many things and have no idea what is going on, can you reply. Thank you!

**Comment by Zwette** [comment]
Sorry for the late reply. You would better try inputting an image of which the size can be divided by 16.
