### ISSUE TITLE
wavelet transform

### ISSUE THREAD

**Issue by Aaronwangz** [Easquel/WaveDM#5]
Thank you very much for sharing, and I would like to ask how you trained the wavelet transform part to get the weights.Looking forward to hearing from you

**Comment by Easquel** [comment]
The weights are provided by the authors of the paper "Wavelet-Based Dual-Branch Network for Image Demoireing".

**Comment by TanMIMI** [comment]
> The weights are provided by the authors of the paper "Wavelet-Based Dual-Branch Network for Image Demoireing".

could you figure out the link or share the weight , I cannot find the weight in  the repository "Wavelet-Based Dual-Branch Network for Image Demoireing", thank you so much!
